/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'scam' : IDL.Null,
  'spam' : IDL.Null,
  'legitimate' : IDL.Null,
  'telemarketer' : IDL.Null,
  'robocall' : IDL.Null,
  'unknown' : IDL.Null,
});
export const CallerIDRecord = IDL.Record({
  'reportCount' : IDL.Nat,
  'name' : IDL.Text,
  'number' : IDL.Text,
  'spamRisk' : IDL.Nat,
  'category' : Category,
  'carrier' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const CallHistoryEntry = IDL.Record({
  'action' : IDL.Variant({
    'report' : IDL.Null,
    'call' : IDL.Null,
    'lookup' : IDL.Null,
  }),
  'number' : IDL.Text,
  'timestamp' : Time,
});
export const ContactNote = IDL.Record({
  'note' : IDL.Text,
  'createdAt' : Time,
  'number' : IDL.Text,
});
export const NumberReport = IDL.Record({
  'user' : IDL.Principal,
  'reportType' : IDL.Variant({ 'spam' : IDL.Null, 'legitimate' : IDL.Null }),
  'number' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addContactNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateCallerID' : IDL.Func([CallerIDRecord], [], []),
  'createIfNotFound' : IDL.Func([IDL.Text], [CallerIDRecord], []),
  'getAllCallerIDs' : IDL.Func([], [IDL.Vec(CallerIDRecord)], ['query']),
  'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistoryEntry)], ['query']),
  'getCallerID' : IDL.Func([IDL.Text], [CallerIDRecord], ['query']),
  'getContactNotes' : IDL.Func([], [IDL.Vec(ContactNote)], ['query']),
  'getNumberReports' : IDL.Func([IDL.Text], [IDL.Vec(NumberReport)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'logCall' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'report' : IDL.Null,
          'call' : IDL.Null,
          'lookup' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'numberExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'reportNumber' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'spam' : IDL.Null, 'legitimate' : IDL.Null })],
      [],
      [],
    ),
  'searchNumber' : IDL.Func([IDL.Text], [IDL.Opt(CallerIDRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'scam' : IDL.Null,
    'spam' : IDL.Null,
    'legitimate' : IDL.Null,
    'telemarketer' : IDL.Null,
    'robocall' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const CallerIDRecord = IDL.Record({
    'reportCount' : IDL.Nat,
    'name' : IDL.Text,
    'number' : IDL.Text,
    'spamRisk' : IDL.Nat,
    'category' : Category,
    'carrier' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const CallHistoryEntry = IDL.Record({
    'action' : IDL.Variant({
      'report' : IDL.Null,
      'call' : IDL.Null,
      'lookup' : IDL.Null,
    }),
    'number' : IDL.Text,
    'timestamp' : Time,
  });
  const ContactNote = IDL.Record({
    'note' : IDL.Text,
    'createdAt' : Time,
    'number' : IDL.Text,
  });
  const NumberReport = IDL.Record({
    'user' : IDL.Principal,
    'reportType' : IDL.Variant({ 'spam' : IDL.Null, 'legitimate' : IDL.Null }),
    'number' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addContactNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateCallerID' : IDL.Func([CallerIDRecord], [], []),
    'createIfNotFound' : IDL.Func([IDL.Text], [CallerIDRecord], []),
    'getAllCallerIDs' : IDL.Func([], [IDL.Vec(CallerIDRecord)], ['query']),
    'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistoryEntry)], ['query']),
    'getCallerID' : IDL.Func([IDL.Text], [CallerIDRecord], ['query']),
    'getContactNotes' : IDL.Func([], [IDL.Vec(ContactNote)], ['query']),
    'getNumberReports' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NumberReport)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'logCall' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'report' : IDL.Null,
            'call' : IDL.Null,
            'lookup' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'numberExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'reportNumber' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'spam' : IDL.Null, 'legitimate' : IDL.Null })],
        [],
        [],
      ),
    'searchNumber' : IDL.Func([IDL.Text], [IDL.Opt(CallerIDRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };