/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallHistoryEntry {
  'action' : { 'report' : null } |
    { 'call' : null } |
    { 'lookup' : null },
  'number' : string,
  'timestamp' : Time,
}
export interface CallerIDRecord {
  'reportCount' : bigint,
  'name' : string,
  'number' : string,
  'spamRisk' : bigint,
  'category' : Category,
  'carrier' : string,
  'location' : string,
}
export type Category = { 'scam' : null } |
  { 'spam' : null } |
  { 'legitimate' : null } |
  { 'telemarketer' : null } |
  { 'robocall' : null } |
  { 'unknown' : null };
export interface ContactNote {
  'note' : string,
  'createdAt' : Time,
  'number' : string,
}
export interface NumberReport {
  'user' : Principal,
  'reportType' : { 'spam' : null } |
    { 'legitimate' : null },
  'number' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addContactNote' : ActorMethod<[string, string], undefined>,
  'addOrUpdateCallerID' : ActorMethod<[CallerIDRecord], undefined>,
  'createIfNotFound' : ActorMethod<[string], CallerIDRecord>,
  'getAllCallerIDs' : ActorMethod<[], Array<CallerIDRecord>>,
  'getCallHistory' : ActorMethod<[], Array<CallHistoryEntry>>,
  'getCallerID' : ActorMethod<[string], CallerIDRecord>,
  'getContactNotes' : ActorMethod<[], Array<ContactNote>>,
  'getNumberReports' : ActorMethod<[string], Array<NumberReport>>,
  'initialize' : ActorMethod<[], undefined>,
  'logCall' : ActorMethod<
    [string, { 'report' : null } | { 'call' : null } | { 'lookup' : null }],
    undefined
  >,
  'numberExists' : ActorMethod<[string], boolean>,
  'reportNumber' : ActorMethod<
    [string, { 'spam' : null } | { 'legitimate' : null }],
    undefined
  >,
  'searchNumber' : ActorMethod<[string], [] | [CallerIDRecord]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];