/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CallHistoryEntry {
    action: Variant_report_call_lookup;
    number: string;
    timestamp: Time;
}
export interface ContactNote {
    note: string;
    createdAt: Time;
    number: string;
}
export interface NumberReport {
    user: Principal;
    reportType: Variant_spam_legitimate;
    number: string;
    timestamp: Time;
}
export type Time = bigint;
export interface CallerIDRecord {
    reportCount: bigint;
    name: string;
    number: string;
    spamRisk: bigint;
    category: Category;
    carrier: string;
    location: string;
}
export enum Category {
    scam = "scam",
    spam = "spam",
    legitimate = "legitimate",
    telemarketer = "telemarketer",
    robocall = "robocall",
    unknown_ = "unknown"
}
export enum Variant_report_call_lookup {
    report = "report",
    call = "call",
    lookup = "lookup"
}
export enum Variant_spam_legitimate {
    spam = "spam",
    legitimate = "legitimate"
}
export interface backendInterface {
    addContactNote(number: string, note: string): Promise<void>;
    addOrUpdateCallerID(record: CallerIDRecord): Promise<void>;
    createIfNotFound(number: string): Promise<CallerIDRecord>;
    getAllCallerIDs(): Promise<Array<CallerIDRecord>>;
    getCallHistory(): Promise<Array<CallHistoryEntry>>;
    getCallerID(number: string): Promise<CallerIDRecord>;
    getContactNotes(): Promise<Array<ContactNote>>;
    getNumberReports(number: string): Promise<Array<NumberReport>>;
    initialize(): Promise<void>;
    logCall(number: string, action: Variant_report_call_lookup): Promise<void>;
    numberExists(number: string): Promise<boolean>;
    reportNumber(number: string, reportType: Variant_spam_legitimate): Promise<void>;
    searchNumber(number: string): Promise<CallerIDRecord | null>;
}
import type { CallHistoryEntry as _CallHistoryEntry, CallerIDRecord as _CallerIDRecord, Category as _Category, NumberReport as _NumberReport, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContactNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactNote(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateCallerID(arg0: CallerIDRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCallerID(to_candid_CallerIDRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCallerID(to_candid_CallerIDRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createIfNotFound(arg0: string): Promise<CallerIDRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createIfNotFound(arg0);
                return from_candid_CallerIDRecord_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIfNotFound(arg0);
            return from_candid_CallerIDRecord_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCallerIDs(): Promise<Array<CallerIDRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCallerIDs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCallerIDs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallHistory(): Promise<Array<CallHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallHistory();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallHistory();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerID(arg0: string): Promise<CallerIDRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerID(arg0);
                return from_candid_CallerIDRecord_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerID(arg0);
            return from_candid_CallerIDRecord_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactNotes(): Promise<Array<ContactNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactNotes();
            return result;
        }
    }
    async getNumberReports(arg0: string): Promise<Array<NumberReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNumberReports(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNumberReports(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async logCall(arg0: string, arg1: Variant_report_call_lookup): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCall(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCall(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async numberExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.numberExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.numberExists(arg0);
            return result;
        }
    }
    async reportNumber(arg0: string, arg1: Variant_spam_legitimate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportNumber(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportNumber(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchNumber(arg0: string): Promise<CallerIDRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNumber(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNumber(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CallHistoryEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallHistoryEntry): CallHistoryEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CallerIDRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallerIDRecord): CallerIDRecord {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_NumberReport_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NumberReport): NumberReport {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallerIDRecord]): CallerIDRecord | null {
    return value.length === 0 ? null : from_candid_CallerIDRecord_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: {
        report: null;
    } | {
        call: null;
    } | {
        lookup: null;
    };
    number: string;
    timestamp: _Time;
}): {
    action: Variant_report_call_lookup;
    number: string;
    timestamp: Time;
} {
    return {
        action: from_candid_variant_n13(_uploadFile, _downloadFile, value.action),
        number: value.number,
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    reportType: {
        spam: null;
    } | {
        legitimate: null;
    };
    number: string;
    timestamp: _Time;
}): {
    user: Principal;
    reportType: Variant_spam_legitimate;
    number: string;
    timestamp: Time;
} {
    return {
        user: value.user,
        reportType: from_candid_variant_n17(_uploadFile, _downloadFile, value.reportType),
        number: value.number,
        timestamp: value.timestamp
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reportCount: bigint;
    name: string;
    number: string;
    spamRisk: bigint;
    category: _Category;
    carrier: string;
    location: string;
}): {
    reportCount: bigint;
    name: string;
    number: string;
    spamRisk: bigint;
    category: Category;
    carrier: string;
    location: string;
} {
    return {
        reportCount: value.reportCount,
        name: value.name,
        number: value.number,
        spamRisk: value.spamRisk,
        category: from_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        carrier: value.carrier,
        location: value.location
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    report: null;
} | {
    call: null;
} | {
    lookup: null;
}): Variant_report_call_lookup {
    return "report" in value ? Variant_report_call_lookup.report : "call" in value ? Variant_report_call_lookup.call : "lookup" in value ? Variant_report_call_lookup.lookup : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spam: null;
} | {
    legitimate: null;
}): Variant_spam_legitimate {
    return "spam" in value ? Variant_spam_legitimate.spam : "legitimate" in value ? Variant_spam_legitimate.legitimate : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scam: null;
} | {
    spam: null;
} | {
    legitimate: null;
} | {
    telemarketer: null;
} | {
    robocall: null;
} | {
    unknown: null;
}): Category {
    return "scam" in value ? Category.scam : "spam" in value ? Category.spam : "legitimate" in value ? Category.legitimate : "telemarketer" in value ? Category.telemarketer : "robocall" in value ? Category.robocall : "unknown" in value ? Category.unknown : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallHistoryEntry>): Array<CallHistoryEntry> {
    return value.map((x)=>from_candid_CallHistoryEntry_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NumberReport>): Array<NumberReport> {
    return value.map((x)=>from_candid_NumberReport_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallerIDRecord>): Array<CallerIDRecord> {
    return value.map((x)=>from_candid_CallerIDRecord_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CallerIDRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallerIDRecord): _CallerIDRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reportCount: bigint;
    name: string;
    number: string;
    spamRisk: bigint;
    category: Category;
    carrier: string;
    location: string;
}): {
    reportCount: bigint;
    name: string;
    number: string;
    spamRisk: bigint;
    category: _Category;
    carrier: string;
    location: string;
} {
    return {
        reportCount: value.reportCount,
        name: value.name,
        number: value.number,
        spamRisk: value.spamRisk,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        carrier: value.carrier,
        location: value.location
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_report_call_lookup): {
    report: null;
} | {
    call: null;
} | {
    lookup: null;
} {
    return value == Variant_report_call_lookup.report ? {
        report: null
    } : value == Variant_report_call_lookup.call ? {
        call: null
    } : value == Variant_report_call_lookup.lookup ? {
        lookup: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_spam_legitimate): {
    spam: null;
} | {
    legitimate: null;
} {
    return value == Variant_spam_legitimate.spam ? {
        spam: null
    } : value == Variant_spam_legitimate.legitimate ? {
        legitimate: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    scam: null;
} | {
    spam: null;
} | {
    legitimate: null;
} | {
    telemarketer: null;
} | {
    robocall: null;
} | {
    unknown: null;
} {
    return value == Category.scam ? {
        scam: null
    } : value == Category.spam ? {
        spam: null
    } : value == Category.legitimate ? {
        legitimate: null
    } : value == Category.telemarketer ? {
        telemarketer: null
    } : value == Category.robocall ? {
        robocall: null
    } : value == Category.unknown ? {
        unknown_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
